//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialNetwork.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot@gmail.com.
        /// </summary>
        internal static string BotEmail {
            get {
                return ResourceManager.GetString("BotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botty.
        /// </summary>
        internal static string BotFirstName {
            get {
                return ResourceManager.GetString("BotFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        internal static string BotLastName {
            get {
                return ResourceManager.GetString("BotLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultHandler.
        /// </summary>
        internal static string DefaultHandler {
            get {
                return ResourceManager.GetString("DefaultHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don`t know what to say..
        /// </summary>
        internal static string DontKnowAnswer {
            get {
                return ResourceManager.GetString("DontKnowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpHandler.
        /// </summary>
        internal static string HelpHandler {
            get {
                return ResourceManager.GetString("HelpHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MathHandler.
        /// </summary>
        internal static string MathHandler {
            get {
                return ResourceManager.GetString("MathHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don&amp;apos;t know this word..
        /// </summary>
        internal static string searchingTextDoesNotExistMessage {
            get {
                return ResourceManager.GetString("DefaultHabdler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatIsHandler.
        /// </summary>
        internal static string WhatIsHandler {
            get {
                return ResourceManager.GetString("WhatIsHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/w/api.php?format=xml&amp;amp;action=query&amp;amp;prop=extracts&amp;amp;titles=.
        /// </summary>
        internal static string wikiApi {
            get {
                return ResourceManager.GetString("wikiApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/.
        /// </summary>
        internal static string wikiURL {
            get {
                return ResourceManager.GetString("wikiURL", resourceCulture);
            }
        }
    }
}
