//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialNetwork.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom message list was saved in {0}..
        /// </summary>
        internal static string CustomMessageListSaved {
            get {
                return ResourceManager.GetString("CustomMessageListSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom user list was saved in {0}..
        /// </summary>
        internal static string CustomUserListSaved {
            get {
                return ResourceManager.GetString("CustomUserListSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail {0} is already used..
        /// </summary>
        internal static string ExceptionRegisterExistingEmail {
            get {
                return ResourceManager.GetString("ExceptionRegisterExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data format ..
        /// </summary>
        internal static string IncorrectInputData {
            get {
                return ResourceManager.GetString("IncorrectInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login or password is incorrect.
        /// </summary>
        internal static string IncorrectUserData {
            get {
                return ResourceManager.GetString("IncorrectUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to register user with existing email: {0}..
        /// </summary>
        internal static string LogRegisterExistingEmail {
            get {
                return ResourceManager.GetString("LogRegisterExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message list was saved in {0}..
        /// </summary>
        internal static string MessageListSaved {
            get {
                return ResourceManager.GetString("MessageListSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} sent a message to user {1}..
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user to register (null user reference)..
        /// </summary>
        internal static string NullUserReference {
            get {
                return ResourceManager.GetString("NullUserReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} profile was deleted..
        /// </summary>
        internal static string ProfileDeleted {
            get {
                return ResourceManager.GetString("ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been registered successfully..
        /// </summary>
        internal static string RegistrationFinished {
            get {
                return ResourceManager.GetString("RegistrationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list was saved in {0}..
        /// </summary>
        internal static string UserListSaved {
            get {
                return ResourceManager.GetString("UserListSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} logged out.
        /// </summary>
        internal static string UserLoggedOut {
            get {
                return ResourceManager.GetString("UserLoggedOut", resourceCulture);
            }
        }
    }
}
