//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Web.WebApiWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialNetwork.Web.WebApiWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Image/Create.
        /// </summary>
        internal static string ImageCreatePath {
            get {
                return ResourceManager.GetString("ImageCreatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Friends/add.
        /// </summary>
        internal static string RouteAddFriend {
            get {
                return ResourceManager.GetString("RouteAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Friends/{0}.
        /// </summary>
        internal static string RouteFriendsById {
            get {
                return ResourceManager.GetString("RouteFriendsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Image/{0}.
        /// </summary>
        internal static string RouteGetImage {
            get {
                return ResourceManager.GetString("RouteGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /LoginApi/ExternalLogin.
        /// </summary>
        internal static string RouteLogIn {
            get {
                return ResourceManager.GetString("RouteLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /LoginApi/ExternalLogout.
        /// </summary>
        internal static string RouteLogOut {
            get {
                return ResourceManager.GetString("RouteLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/MessageHistory?userId={0}&amp;userFriendId={1}.
        /// </summary>
        internal static string RouteMessageHistory {
            get {
                return ResourceManager.GetString("RouteMessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Friends?user1={0}&amp;user2={1}.
        /// </summary>
        internal static string RouteMutualFriends {
            get {
                return ResourceManager.GetString("RouteMutualFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Friends?user1={0}&amp;user2Email={1}.
        /// </summary>
        internal static string RouteMutualFriendsWithEmail {
            get {
                return ResourceManager.GetString("RouteMutualFriendsWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RegistrationApi/Register.
        /// </summary>
        internal static string RouteRegister {
            get {
                return ResourceManager.GetString("RouteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/MessageSearching/{0}.
        /// </summary>
        internal static string RouteSearchMessageById {
            get {
                return ResourceManager.GetString("RouteSearchMessageById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/MessageSearching?receiverId={0}.
        /// </summary>
        internal static string RouteSearchMessageByReceiverId {
            get {
                return ResourceManager.GetString("RouteSearchMessageByReceiverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/MessageSearching?senderId={0}.
        /// </summary>
        internal static string RouteSearchMessageBySenderId {
            get {
                return ResourceManager.GetString("RouteSearchMessageBySenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/MessageSearching?text={0}.
        /// </summary>
        internal static string RouteSearchMessageByText {
            get {
                return ResourceManager.GetString("RouteSearchMessageByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/MessageSearching?userId={0}.
        /// </summary>
        internal static string RouteSearchMessageByUserId {
            get {
                return ResourceManager.GetString("RouteSearchMessageByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/UserSearching?email={0}.
        /// </summary>
        internal static string RouteSearchUserByEmail {
            get {
                return ResourceManager.GetString("RouteSearchUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/UserSearching?firstName={0}&amp;lastName={1}.
        /// </summary>
        internal static string RouteSearchUserByFLName {
            get {
                return ResourceManager.GetString("RouteSearchUserByFLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/UserSearching?firstName={0}.
        /// </summary>
        internal static string RouteSearchUserByFName {
            get {
                return ResourceManager.GetString("RouteSearchUserByFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/UserSearching/{0}.
        /// </summary>
        internal static string RouteSearchUserById {
            get {
                return ResourceManager.GetString("RouteSearchUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/UserSearching?lastName={0}.
        /// </summary>
        internal static string RouteSearchUserByLName {
            get {
                return ResourceManager.GetString("RouteSearchUserByLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/UserSearching?emailOrLogin={0}.
        /// </summary>
        internal static string RouteSearchUserByLoginOrEmail {
            get {
                return ResourceManager.GetString("RouteSearchUserByLoginOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/messanger/email.
        /// </summary>
        internal static string RouteSendEmailMessage {
            get {
                return ResourceManager.GetString("RouteSendEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/messanger/guid.
        /// </summary>
        internal static string RouteSendGuidMessage {
            get {
                return ResourceManager.GetString("RouteSendGuidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/endpoint.
        /// </summary>
        internal static string RouteSetEndPoint {
            get {
                return ResourceManager.GetString("RouteSetEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/ShortestUserPath?user1={0}&amp;user2={1}.
        /// </summary>
        internal static string RouteShortestUserPath {
            get {
                return ResourceManager.GetString("RouteShortestUserPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/ShortestUserPath?user1={0}&amp;user2Email={1}.
        /// </summary>
        internal static string RouteShortestUserPathEmail {
            get {
                return ResourceManager.GetString("RouteShortestUserPathEmail", resourceCulture);
            }
        }
    }
}
