//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.UI.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialNetwork.UI.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string CommandExit {
            get {
                return ResourceManager.GetString("CommandExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        internal static string CommandExport {
            get {
                return ResourceManager.GetString("CommandExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find.
        /// </summary>
        internal static string CommandFind {
            get {
                return ResourceManager.GetString("CommandFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        internal static string CommandFriends {
            get {
                return ResourceManager.GetString("CommandFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        internal static string CommandLogIn {
            get {
                return ResourceManager.GetString("CommandLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        internal static string CommandLogOut {
            get {
                return ResourceManager.GetString("CommandLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string CommandPath {
            get {
                return ResourceManager.GetString("CommandPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        internal static string CommandSend {
            get {
                return ResourceManager.GetString("CommandSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        internal static string CommandSignUp {
            get {
                return ResourceManager.GetString("CommandSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlPath.
        /// </summary>
        internal static string ConfigStoragePath {
            get {
                return ResourceManager.GetString("ConfigStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : Firstly log out, than you will be able to log in&quot;.
        /// </summary>
        internal static string ErrorDoubleLogIn {
            get {
                return ResourceManager.GetString("ErrorDoubleLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Email isn`t correct..
        /// </summary>
        internal static string ErrorNotValidEmail {
            get {
                return ResourceManager.GetString("ErrorNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Password must have at least {0} symbols..
        /// </summary>
        internal static string ErrorNotValidPassword {
            get {
                return ResourceManager.GetString("ErrorNotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Expected argument -u|--user or   -m|--message.
        /// </summary>
        internal static string ErrorUnknownFind {
            get {
                return ResourceManager.GetString("ErrorUnknownFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : Must be &quot;send -m|--message&quot;.
        /// </summary>
        internal static string ErrorUnknownSend {
            get {
                return ResourceManager.GetString("ErrorUnknownSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: User with this email wasn`t found..
        /// </summary>
        internal static string ErrorUnknownUserEmail {
            get {
                return ResourceManager.GetString("ErrorUnknownUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : Must be &quot;export -u|--user   -m|--message  -f|--file=&lt;file_name&gt;&quot;.
        /// </summary>
        internal static string ErrorUnkownExport {
            get {
                return ResourceManager.GetString("ErrorUnkownExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : Some error heppaned while transfering data and getting response from server..
        /// </summary>
        internal static string ErrorWhileDataTransfering {
            get {
                return ResourceManager.GetString("ErrorWhileDataTransfering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Something wrong with command parameters. Try &apos;--help&apos; or &apos;help&apos; ..
        /// </summary>
        internal static string ErrorWrongParams {
            get {
                return ResourceManager.GetString("ErrorWrongParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was successfully exported to {0}.cvs file in &quot;{1}&quot; directory..
        /// </summary>
        internal static string InfoDataExportedToCVS {
            get {
                return ResourceManager.GetString("InfoDataExportedToCVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        internal static string InfoEmail {
            get {
                return ResourceManager.GetString("InfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully registred.
        /// </summary>
        internal static string InfoEndedSignUp {
            get {
                return ResourceManager.GetString("InfoEndedSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name : .
        /// </summary>
        internal static string InfoFirstName {
            get {
                return ResourceManager.GetString("InfoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &quot;log in&quot; or &quot;sign up&quot;. To get available command list enter &apos;help&apos;.
        /// </summary>
        internal static string InfoFirsUsage {
            get {
                return ResourceManager.GetString("InfoFirsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our social network.
        /// </summary>
        internal static string InfoGreeting {
            get {
                return ResourceManager.GetString("InfoGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name : .
        /// </summary>
        internal static string InfoLastName {
            get {
                return ResourceManager.GetString("InfoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login :.
        /// </summary>
        internal static string InfoLogin {
            get {
                return ResourceManager.GetString("InfoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message. Must end with.
        /// </summary>
        internal static string InfoMessageEntering {
            get {
                return ResourceManager.GetString("InfoMessageEntering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was successfully sent.
        /// </summary>
        internal static string InfoMessageSuccessfullySend {
            get {
                return ResourceManager.GetString("InfoMessageSuccessfullySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error happened and message wasnt properly sent..
        /// </summary>
        internal static string InfoMessageWasntSend {
            get {
                return ResourceManager.GetString("InfoMessageWasntSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string InfoNewCommandLine {
            get {
                return ResourceManager.GetString("InfoNewCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password : .
        /// </summary>
        internal static string InfoPassword {
            get {
                return ResourceManager.GetString("InfoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started signing up user.
        /// </summary>
        internal static string InfoStartedSignUp {
            get {
                return ResourceManager.GetString("InfoStartedSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try `--help&apos; for more information..
        /// </summary>
        internal static string ParserHelpOffer {
            get {
                return ResourceManager.GetString("ParserHelpOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command name to execute. In order to get all commands available to your authorized rights type &apos;help&apos;.
        /// </summary>
        internal static string ParserOptionCommandInfo {
            get {
                return ResourceManager.GetString("ParserOptionCommandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets user email for command.
        /// </summary>
        internal static string ParserOptionEmail {
            get {
                return ResourceManager.GetString("ParserOptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets file name to export in.
        /// </summary>
        internal static string ParserOptionFileName {
            get {
                return ResourceManager.GetString("ParserOptionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help.
        /// </summary>
        internal static string ParserOptionHelp {
            get {
                return ResourceManager.GetString("ParserOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this command with message.
        /// </summary>
        internal static string ParserOptionMessage {
            get {
                return ResourceManager.GetString("ParserOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;friends&apos; will return all common friends between you and specified registred user.
        /// </summary>
        internal static string ParserOptionMutual {
            get {
                return ResourceManager.GetString("ParserOptionMutual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search would be done in received messages.
        /// </summary>
        internal static string ParserOptionRecieved {
            get {
                return ResourceManager.GetString("ParserOptionRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search would be done in sended messages.
        /// </summary>
        internal static string ParserOptionSended {
            get {
                return ResourceManager.GetString("ParserOptionSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this command with user.
        /// </summary>
        internal static string ParserOptionUser {
            get {
                return ResourceManager.GetString("ParserOptionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unknown command or some argument wasn`t recognized.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string UsageExit {
            get {
                return ResourceManager.GetString("UsageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export -u|--user   -m|--message  -f|--file=&lt;file_name&gt;.
        /// </summary>
        internal static string UsageExport {
            get {
                return ResourceManager.GetString("UsageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find [-u|--user  -e|--email=&lt;user_emai&gt;]   [-m|--message  -r|--received  -s|--sended].
        /// </summary>
        internal static string UsageFind {
            get {
                return ResourceManager.GetString("UsageFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends [--mutual   -e|--email=&lt;user_email&gt;].
        /// </summary>
        internal static string UsageFriends {
            get {
                return ResourceManager.GetString("UsageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string UsageHelp {
            get {
                return ResourceManager.GetString("UsageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in/out.
        /// </summary>
        internal static string UsageLog {
            get {
                return ResourceManager.GetString("UsageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path -e|--email=&lt;user_email&gt;.
        /// </summary>
        internal static string UsagePath {
            get {
                return ResourceManager.GetString("UsagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send -m|--message  -e|--email=&lt;user_email&gt;.
        /// </summary>
        internal static string UsageSend {
            get {
                return ResourceManager.GetString("UsageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        internal static string UsageSign {
            get {
                return ResourceManager.GetString("UsageSign", resourceCulture);
            }
        }
    }
}
